from enum import Enum

DISEASE_NAMES = ["SARS-CoV"]
DEFAULT_PARTICLE_SIZE = 10
DEFAULT_PARTICLE_COUNT = 50
DEFAULT_INFECTED_COUNT = 1
DEFAULT_INFECTION_RATE = 1
DEFAULT_DEATH_RATE = 0.03
MASK_INFECTION_REDUCTION = 0.65
MASK_RADIUS_REDUCTION = 0.8 # radius reduction not implemented yet. Only infection rate reduction.
DEFAULT_INFECTION_TIME = 500
DEFAULT_RECOVERED_TIME = 300

SOCIAL_DISTANCING_RADIUS_MULTIPLIER = 4

DEFAULT_TARGET_WAITING_DURATION = 100
DEFAULT_VISITING_COUNT = 2
DEFAULT_NO_VISIT_DURATION = 200

class Status(Enum):
    HEALTHY = "h"
    INFECTED = "i"
    DEAD = "d"
    RECOVERED = "r"

class Movement(Enum):
    UNDIRECTED = "r"
    DIRECTED = "t"
    DIAGONAL = "xy"

