import os
ABSOLUTE_VALUE_STRING = "Anzahl"
PERCENTAGE_VALUE_STRING = "%"
TREE_NODE_VERTICAL_DISTANCE = 65
TREE_NODE_TEXT_VERTICAL_DISTANCE = 10
TREE_NODE_HORIZONTAL_DISTANCE = 30
TREE_NODE_VERTICAL_LINE_LENGTH = 65
TREE_NODE_CHILD_HORIZONTAL_LINE_LENGTH = 10
TREE_NODE_NEXT_CHILD_HORIZONTAL_LINE_LENGTH = 30

DEFAULT_INFECTED_DAYS = 10
DEFAULT_RECOVERED_DAYS = 5

EXTERMINATED_MUTATION_COLOR_VALUES = (181,181,181,255)
INFECTED_COLOR_VALUES = (255, 0, 0, 128)
HEALTHY_COLOR_VALUES = (0, 255, 33, 255)
DEAD_COLOR_VALUES = (136, 136, 136, 128)
RECOVERED_COLOR_VALUES = (12, 0, 193, 128)

SIMULATION_END_TEXT_COLOR = (173,0,0,150)

DNA_IMAGE_OFFSET = 50
DNA_IMAGE_Y_CORRECTION = 5  # Corrects y coordinate of dna image to match y coordinate of text visibly.

VACCINE_IMAGE_X_OFFSET = 240

CROSS_IMAGE_PATH = os.path.abspath(r".\resources\images\cross50px.png")
DNA_IMAGE_PATH = os.path.abspath(r".\resources\images\dna50px.png")

ICON_IMAGE_PATH = os.path.abspath(r".\resources\icon.png")

VACCINE_IMAGE_PATH = os.path.abspath(r".\resources\images\vaccine30px.png")

WINDOW_TITLE = "Pandemie Simulator"